### ISSUE TITLE
new SI figures

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/toxManuscript#16]
Figure concept for SI:
1. Heat map with sites on the x-axis, organized like the bar chart tab. AOP on the y-axis. color the heat map by EAR like is done in Fig 4. Limit to AOPs that have EAR > 10^-3 for at least 10 sites to keep it focused on the priorities.

2. Heat map with sites on the x-axis, organized like the bar chart tab. Chemicals on the y-axis. Color the heat map by EAR like is done in Fig 4. Limit to chemicals that have EAR > 10^-3 to keep it sane.
--start this one using the Heat map tab from the app, but reducing the chemicals that have EAR > 10^-3 to keep it focused. We may or may not need the categories on the right, but leave them in for now.

**Comment by ldecicco-USGS** [comment]
Here's 1:
![si1](https://user-images.githubusercontent.com/1105215/40444993-78f8efc0-5e90-11e8-9c75-fcadabe1bd00.png)

**Comment by ldecicco-USGS** [comment]
I guess I don't see the difference between what you described and our standard `plot_tox_heatmap" with the "Chemical" category. Here's that:
![si2](https://user-images.githubusercontent.com/1105215/40445599-352f61be-5e92-11e8-93bd-3e5d56afef2f.png)

**Comment by srcorsi-USGS** [comment]
We could use this directly. My initial thought was to reduce chemicals to those with EAR > 10^-3 at 10 or more sites in order to prioritize. Here is how I have it written in the manuscript:
#
For the sake of screening and prioritizing the chemicals with the greatest potential for causing adverse effects at multiple areas within the Great Lakes region, chemicals that were present at a minimum of 10 sites and had EARmax > 10-3 at a minimum of 5 sites were considered. These chemicals included 4-nonylphenol (a detergent metabolite), bisphenol A (used in plastics and epoxy resins), metolachlor and atrazine (herbicides), DEET (insecticide), caffeine, Tris(2-butoxyethyl) phosphate and tributyl phosphate (fire retardants), benzo(a)pyrene and fluoranthene (PAHs), and benzophenone (ultraviolet radiation protection in soaps, fragrances, plastics) (Figure 1). 
#
We could just include the entire graph and somehow highlight the ones that fit this priority criteria. Different colored chnm, bold chnm, asterix in front of the chnm... something to distinguish the ones we talk about in the text.

**Comment by srcorsi-USGS** [comment]
So, differences from the current SI fig 3:
1. remove the class summations from current SI fig 3
2. highlight the chemicals with  EAR > 10^-3 at 10 or more sites in some way.

**Comment by srcorsi-USGS** [comment]
For the AOP heat map, remove the irrelevant AOPs and keep the yes and maybes

**Comment by ldecicco-USGS** [comment]
OK, the colored labels combined with the Classes on the right side make this a very difficult task. I found 1 stackoverflow answer that looked promising:
https://stackoverflow.com/questions/45843759/ggplot2-coloring-axis-text-on-a-faceted-plot
but so far have not been able to get it work for our more complicated graph.
For now, we'll let it be and add colors with Illustrator at the end, unless someone fills me in one an easy way to do it.

**Comment by ldecicco-USGS** [comment]
![si2](https://user-images.githubusercontent.com/1105215/40550202-12abe9f0-5fff-11e8-929d-5319ace73f56.png)

Some overnight suggestions on the `ggplot2` issues made this possible. You need to have the dev version of ggplot2 installed to make it work. The dev version is slated to go to CRAN in a few weeks, so it's pretty safe to install:

```r
devtools::install_github("tidyverse/ggplot2")
```
