### ISSUE TITLE
Figure SI-3

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/toxManuscript#29]
@ldecicco-USGS 
For Fig SI-3 barchart with the number of sites with EAR > 10^-3, add the number of sites where the chemical was detected across the top. This will match with just how we analyzed the data within the manuscript.

**Comment by ldecicco-USGS** [comment]
Take out relevance column

**Comment by ldecicco-USGS** [comment]
Like this?



![si3_chem_counts](https://user-images.githubusercontent.com/1105215/42905321-4b8cd496-8a9d-11e8-9e12-78421c54e064.png)

**Comment by srcorsi-USGS** [comment]
Nope. What was added was the number of sites with EAR > 0.001. What we want is the number of sites where the chemical was detected (including those that did not have EAR > 0.001). In this case, would it be most appropriate to put that number across the top or within the bars like you have it? @ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
Yeah, if it's not just the number in the bar, it should be across the top or bottom, I didn't understand what you were asking for.

**Comment by ldecicco-USGS** [comment]
![image](https://user-images.githubusercontent.com/1105215/42957128-5e576e74-8b47-11e8-862a-059c8e81daed.png)

How about that? Do you prefer that or mixing the bar/text? Since they actually have the same scale, we could do it visually like this (unlike a lot of our other plots)

**Comment by srcorsi-USGS** [comment]
Yes, I like this format. Legend should read:
Detected
> 10-3

**Comment by ldecicco-USGS** [comment]
![si3_chem_counts](https://user-images.githubusercontent.com/1105215/42963395-bbeb3cac-8b59-11e8-8c50-21170753a62a.png)
