### ISSUE TITLE
tq summation update

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/toxManuscript#3]
Verify that the new fig 1 and data_setup_wq_benchmarks.R do not sum Tq values for benchmarks from multiple endpoints.  @ldecicco-USGS 

Question to ponder: should we be summing for multiple chemicals that have influence for the same benchmark (e.g. when multiple chemicals all have "acute" benchmark hits, do we add them together? My gut feeling is no. It is definitely possible that they could be additive, but modes of biological action may be different for different chemicals for "acute" or "chronic" toxicity. I think there is no right answer here, but it will vary depending on chemicals.

**Comment by srcorsi-USGS** [comment]
@ldecicco-USGS 
I think this is all resolved with your revisions, correct? If so, feel free to close this one out.

**Comment by ldecicco-USGS** [comment]
Yup!
