### ISSUE TITLE
Manuscript figures

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/toxManuscript#31]
Here, I am keeping a general list of the manuscript figs for our reference. If needed, there will be separate figure-specific issues for details.

1. EAR vs benchmark 4-panel fig
2. Chemical counts for site prioritization
3. Boxplots of EARs by toxcast endpoint with endpoints with AOPs highlighted
4. 2-panel: X-axis = AOP for A. boxplots with EAR, and B. heat map with endpoint
5. AOP networks

**Comment by ldecicco-USGS** [comment]
This seems to work:
```
# Create all the figures....

# Fig 1:
source("fig1_combo_graph.R")
rm(list=ls())
# Fig 2:
source("fig_2_site_counts.R")
rm(list=ls())
# Fig 3:
source("fig_3_endpoint_boxplots.R")
rm(list=ls())
# Fig 4:
source("fig_4_aop_priority.R", print.eval=TRUE)
rm(list=ls())
```
(it's the `create_all_figs.R` script). I'm updating the scripts to toxEval 1.0.0 and ggplot2 3.0.0 notation. I'll push those all up together (with SI fig and tables)
