### ISSUE TITLE
SI Table 6

### ISSUE THREAD

**Issue by ldecicco-USGS** [ldecicco-USGS/toxManuscript#32]
Dan's table of AOP ID, relavence, and justification (no endpoints)

**Comment by srcorsi-USGS** [comment]
Correspondence with Dan indicates that he may prefer keeping the endpoints in. He left it for us to decide though. I lean towards keeping them in since it can be useful to som, fairly easy to do, and just adds a bit of length to an SI table. @ldecicco-USGS

**Comment by srcorsi-USGS** [comment]
This one is in good shape aside from adding in the endpoint names for AOPs 57 and  214. We never gave those to Dan, so they still need to be filled in. If there are multiple, just duplicate info in the other cells for those rows. @ldecicco-USGS
