### ISSUE TITLE
SI Figure 6 revision

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/toxManuscript#35]
For SI fig 6, the Heat map with AOP ID on Y-axis and sites on X-axis, I have added an AO short name to the file SI_6_AOP_relevance With Short AOP name.xlsx. Use these to add Adverse Outcome categories on the right hand side of the heat map.
@ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
![si6_aop_heat](https://user-images.githubusercontent.com/1105215/42904134-a4c636e6-8a99-11e8-803b-f3fab2edcaec.png)

How's that?

**Comment by ldecicco-USGS** [comment]
![si6_aop_heat](https://user-images.githubusercontent.com/1105215/42957764-34acc0ea-8b49-11e8-9916-f5518b367c0d.png)

?

**Comment by srcorsi-USGS** [comment]
This looks good.
Order the categories with 
all relevant ones first, 
then AOP not defined, 
then Not environmentally relevant

**Comment by ldecicco-USGS** [comment]
![si6_aop_heat](https://user-images.githubusercontent.com/1105215/42965611-1dfdb61c-8b60-11e8-84c1-9f9f9bb6b548.png)
