### ISSUE TITLE
New Fig 3

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/toxManuscript#4]
I started the new fig 3, and it has most of what we need. See the script fig3_endpoint_boxplots.R. There are a couple of comments there for enhancements that will be more efficiently done by you as follows:

-put the number of chemicals per endpoint on the right side.
-add color to distinguish endpoints with associated AOPs
@ldecicco-USGS

**Comment by srcorsi-USGS** [comment]
Notation for x-axis has k defined twice. The first should be "i". Do we want to be consistent with the way the are in the formula? So, include chemicals[i], samples[j], and sites[k] or the alternative is [i], [j], and [k] without "chemicals", "samples", and "sites". I think I lean towards the second one with these definitions below:

i = chemicals in specified grouping, j= samples from specified site, k = study sites

but if you lean the other way, I am open to that also. Not sure it matters.

@ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
I'd drop "study" (from study sites)...and I still don't think we need to say "from specified site" with samples....there wouldn't be samples with multiple sites:

![fig3_endpoint_boxplots](https://user-images.githubusercontent.com/1105215/39581769-f4423914-4eb1-11e8-9bd0-6faf82401e0f.png)

My guess is you might be using a different script than me? Our legends are different...I'm doing:

```
source("fig_3_endpoint_boxplots.R")
```

**Comment by srcorsi-USGS** [comment]
I'm using the same script. I just changed the legend labels. Just did an upstream pull and ran it again. Did a PR to make sure you can get exactly what I am doing:

source("fig_3_endpoint_boxplots.R")


![fig3_endpoint_boxplots](https://user-images.githubusercontent.com/1444781/39584441-10f5f932-4eb8-11e8-903b-56f3bae7a861.png)

**Comment by srcorsi-USGS** [comment]
I excluded two BPA endpoints and reran things. Noticed that we don't have y-axis labels. Added that in to figs 3 and 4. Fig 4 worked, fig 3 didn't. Maybe you can have a look at fig 3

**Comment by ldecicco-USGS** [comment]
```
endpoints_sites_hits <- filter(chemicalSummary,EAR > 0) %>%
  group_by(endPoint,site,date) %>%
  summarize(EARsum = sum(EAR)) %>%
  group_by(site,endPoint) %>%
  summarize(EARmax = max(EARsum))
```
