### ISSUE TITLE
SI Fig 7

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/toxManuscript#43]
Somewhere in the mix, the names of the chemicals of the mixtures boxplots were dropped (Fig SI-7A, B, and C). We will need those added back in. See the pdf below (SI7_mixtureBoxplots) vs the one with all of the SI figs that you send Friday to see the difference.
@ldecicco-USGS 

[SI7_mixtureBoxplots.pdf](https://github.com/ldecicco-USGS/toxManuscript/files/2242944/SI7_mixtureBoxplots.pdf)
[SI_figures 2018 07 30.pdf](https://github.com/ldecicco-USGS/toxManuscript/files/2242945/SI_figures.2018.07.30.pdf)

**Comment by ldecicco-USGS** [comment]
I thought we discussed removing the titles and putting them off and just put in the caption. I can put them back, but it was deliberate taking them out.

**Comment by srcorsi-USGS** [comment]
Hmmm, I don't recall. Too many figs and too many decisions. I guess we should decide what will work best. I think my preference is to have them included for each plot so it is quick and easy to tell what chemicals go with what plot. Let's revert back to that.
