### ISSUE TITLE
New Fig 4

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/toxManuscript#5]
For figure 4, I would like to narrow down to priority AOPs as we did when determining what to send to Dan for the AOP networks. There is already code to get there, and I think you (Laura) has developed a script to make this plot for the most part when we were prepping for the HTS conference. @ldecicco-USGS 

As a companion to this, let's consider an SI table(s) that includes AOP priority information on sites and chemicals.

FIGURE 4: Boxplots of EARs for AOPs: Put the number of sites on the left and the number of chemicals on the right. For analysis, define the combos of chemicals that combine to get high EARs for each site as defined by:

1. Sum individual samples by AOP_id
 2. Filter out EAR AOP summations by threshold EAR > xx
Develop boxplot with this for starters.

Additional consideration for analysis: perhaps we can devise something for a supp table or fig, but this is how the AOP networks were developed.
 3. Determine percent of EAR contributed by each chemical for each AOP
 4. Filter out chemicals with less than x% contribution (x = 1%)
 5. List chemicals for urban and ag sites that are remaining for each AOP,
    prioritize these by % contribution to AOP EARs
 6. Determine how many sites each of the AOPs are relevant to. Keep a list of 
    sites for each AOP
 7. At each priority site for each priority AOP, determine which chemicals are 
    highest priority for each chemical from step #5

**Comment by ldecicco-USGS** [comment]
OK, I started some work here:
https://github.com/ldecicco-USGS/toxManuscript/blob/master/fig_4_aop_priority.R

It makes a graph like this (AOP_EAR_thres <- 0.01):
![fig4_aopid_boxplots](https://user-images.githubusercontent.com/1105215/39591894-c727de70-4eca-11e8-89c4-8f5cea8a338d.png)

here's 0.1 threshold:
![fig4_aopid_boxplots](https://user-images.githubusercontent.com/1105215/39592028-3500684a-4ecb-11e8-91e6-01328fbfde25.png)

And the final table `fractions` I think can be used to get at what you are trying to do in the steps above.

**Comment by srcorsi-USGS** [comment]
OK, it looks like we have a lot of redundant info when there are multiple AOPs for one endpoint. We could potentially be more efficient with space if we combined them and somehow indicated which AOPs were represented. So, it would actually be the same as an endpoint boxplot with the non-AOP endpoints filtered out. Then the labels would be some form of vector of AOP numbers rather than the endpoint name. This idea will look really ugly on the y-axis. Any ideas to improve this idea?

**Comment by srcorsi-USGS** [comment]
For consistency/continuity between figs 3 and 4, let's make the boxes orange in fig 4.

**Comment by srcorsi-USGS** [comment]
Yes, let's combine the redundant AOPs somehow. Something like this:

1. Begin with AOP numbers
2. Determine which AOPs have the same endpoints/EARs contributing to them
3. Filter to the unique endpoints/EARs and develop a vector of unique AOPs for each
4. Start with exploration by Boxplots of the unique endpoints/EARs, labeled by the vectors of AOPs
5. Also provide a table that has columns:
Endpoint  |  AOP_vector  |   maxEAR  |  medianEAR

This will help define things when there are multiple AOPs for an endpiont. Now we need to consider multiple endpoints for a given AOP. then we need to define when we have the same group of endpoints hitting more than one AOP.

So, unique groups of endpoints with multiple AOPs should be grouped together somehow.
This table might help:

AOP  |  endpoint_vector  | maxEAR | medianEAR

then we can determine unique endpoint_vectors for each AOP and run a boxplot.
Perhaps we should talk in person before spending coding time on it?

**Comment by ldecicco-USGS** [comment]
When you say "maxEAR | medianEAR"...do you mean overall of all the EAR measurements...or do you mean our standard max/median of the sites (summing the EARs by sample)?

**Comment by srcorsi-USGS** [comment]
For the endpoints
Endpoint | AOP_vector | maxEAR | medianEAR

max is the max of the endpoint EAR summations being used

for AOPs
AOP | endpoint_vector | maxEAR | medianEAR

max is the max for the AOP EAR summations being used

**Comment by ldecicco-USGS** [comment]
For the record...I don't think there's a single AOP that has the exact same endpoint contributions as another AOP, and likewise I don't think there's an endpoint that contributes to the same set of AOPs as anther endpoint.

**Comment by srcorsi-USGS** [comment]
To make this more manageable and zero in on priority AOPs and endpoints, we should do as we are in fig 3 and limit to endpoints and aops with siteThreshold = 10 (variable option), so only endpoints and AOPs with hits at 10 or more sites.

**Comment by ldecicco-USGS** [comment]
What about something like this (clean it up of course):
![image](https://user-images.githubusercontent.com/1105215/39843465-c58716c2-53b0-11e8-8257-95a67788c01b.png)

I'm having a hard time following the idea above.

**Comment by ldecicco-USGS** [comment]
Prettied up:

![image](https://user-images.githubusercontent.com/1105215/39875030-14193552-5435-11e8-8301-8b7dd086577b.png)

**Comment by srcorsi-USGS** [comment]
This looks pretty good. I like the concept. Can we put the number of sites for each AOP across the top?
7 AOPs stand out pretty clearly here (29,30,52,53,112,167,200). A couple more make you take extra notice (58,165).
We will need to add Kelly's ToxCast-AOP mapping into the SI as a table, and reference it in the caption.

**Comment by ldecicco-USGS** [comment]
I pushed up the code to get sites up there

**Comment by ldecicco-USGS** [comment]
![image](https://user-images.githubusercontent.com/1105215/39893533-ab7c6b42-5469-11e8-8972-c8a990c826a4.png)

**Comment by srcorsi-USGS** [comment]
OK, I want to make sure I understand this correctly. These are means of the maxEAR for each AOP-endpoint combo for the sites with detections, correct?
One thing that we do need to get out of this is the sum of EARs from all endpoints associated with a given AOP.  Thinking this through, I think that we can get to this by using the current heat map and adding a boxplot above it for each AOP. Here is a conceptual version of what this could look like. Does that formula and description of the formula look right to you?

![image](https://user-images.githubusercontent.com/1444781/39899407-4cc69db2-5481-11e8-978c-0822adfc1b86.png)

**Comment by ldecicco-USGS** [comment]
Making the 2 graphs isn't too hard...lining them up right, is the harder part. This was my best shot:

![aop_cow](https://user-images.githubusercontent.com/1105215/39907014-bf38a69a-54ab-11e8-89c4-43e8b3b5b92b.png)

**Comment by srcorsi-USGS** [comment]
This looks very good. Now for the equation notation, and as I think more about this, we may be double-counting chemical contributions within AOP EAR summations. We might need to talk this through, but here is what I need to get straight--you may be computing things differently than I think:

1. EARs are computed for each endpoint for each chemical by sample
2. EARs for each AOP are summed for each corresponding endpoint by sample
3. Max of samples by site

With this method, there could be multiple endpoints that are influenced by the same chemical for the same AOP. So, is it legit to sum the endpoint EARs, effectively adding effects from the same chemical for different endpoints? 

something like this is currently how it is being done (I think):
EARAOP1 = 
EAR[endpoint1,chemical1,AOP1] + EAR[endpoint2,chemical1,AOP1] + EAR[endpoint3,chemical1,AOP1] + 
EAR[endpoint1,chemical2,AOP1] + EAR[endpoint2,chemical2,AOP1] + EAR[endpoint3,chemical2,AOP1] + 
EAR[endpoint1,chemical3,AOP1] + EAR[endpoint2,chemical3,AOP1] + EAR[endpoint3,chemical3,AOP1]  

I am not sure, but my best guess is that we should take the max EAR for each chemical 

EARAOP1 = 
max(EAR[endpoint1,chemical1,AOP1], EAR[endpoint2,chemical1,AOP1], EAR[endpoint3,chemical1,AOP1]) +
max(EAR[endpoint1,chemical2,AOP1],EAR[endpoint2,chemical2,AOP1],EAR[endpoint3,chemical2,AOP1]) +
max(EAR[endpoint1,chemical3,AOP1],EAR[endpoint2,chemical3,AOP1],EAR[endpoint3,chemical3,AOP1] )

We should meet this morning and discuss the "philosophy" of EAR determination for AOPs and agree on something or formulate a question for Dan and Brett.

**Comment by srcorsi-USGS** [comment]
Questions to answer in discussion with Dan:
1.  Double counting chemicals in AOP EAR computations
2. Taxonomic Relevance 
3. endpoint double count: using the same endpoints with different test durations?

**Comment by ldecicco-USGS** [comment]
After our discussion, here's the current filter

![aop_cow](https://user-images.githubusercontent.com/1105215/39934246-d47ca5ec-550a-11e8-8417-4f81ab5a1e9d.png)

**Comment by ldecicco-USGS** [comment]
![aop_cow](https://user-images.githubusercontent.com/1105215/39936058-e4ca763a-5510-11e8-8aa3-0b7074bb72bc.png)

fiddling with limits

**Comment by srcorsi-USGS** [comment]
Does this look right for the upper panel?
![image](https://user-images.githubusercontent.com/1444781/40199237-7c45dbf4-59de-11e8-9c65-9459a3fd6109.png)

Where i = chemicals, and j = endpoints

**Comment by srcorsi-USGS** [comment]
I think the heat map portion is as simple as this since the AOP and endpoint are defined on the axes:

![image](https://user-images.githubusercontent.com/1444781/40199449-151cc8ce-59df-11e8-8332-5a0247b2bb8b.png)

i = chemicals

**Comment by srcorsi-USGS** [comment]
Maybe this is more appropriate

![image](https://user-images.githubusercontent.com/1444781/40199489-408cc45a-59df-11e8-9b16-24abf615d229.png)

**Comment by ldecicco-USGS** [comment]
The code for the top one now is:
```
boxData <- chemicalSummary %>%
  left_join(AOP, by="endPoint") %>%
  group_by(ID, chnm, site, date) %>%
  summarize(maxEAR = max(EAR, na.rm = TRUE)) %>%
  group_by(ID, site) %>%
  summarize(maxEAR = max(maxEAR)) ...
```
So, is it?
max[max(EAR[i])][j]
i = chemical,
j = AOP

**Comment by srcorsi-USGS** [comment]
OK, for the top (boxplots), I am thinking through this again: I think this is what we should be getting:

After joining chemsummary with AOPs:

1. group by AOP, site, sample, chemical 
2. take max per sample for each chemical
3. Sum these max values by sample (so 
4. Take the max per site
5. Make boxplot

I think it should be this:

`boxData <- chemicalSummary %>%
  filter(EAR>0) %>%
  left_join(AOP, by="endPoint") %>%
              group_by(ID,site,date,chnm) %>%
              summarize(maxEAR = max(EAR, na.rm=TRUE)) %>%
            group_by(ID,site,date) %>%
              summarize(maxEARsum = sum(maxEAR)) %>%
            group_by(ID,site) %>%
              summarize(maxEARsumSite = `max(maxEARsum))`

Looks to me that you are missing a summation by sample after finding the max for each chemical,  sample and site by AOP.

**Comment by srcorsi-USGS** [comment]
why does my code look so ugly? here it is without the code format.

boxData <- chemicalSummary %>%
  filter(EAR>0) %>%
  left_join(AOP, by="endPoint") %>%
              group_by(ID,site,date,chnm) %>%
              summarize(maxEAR = max(EAR, na.rm=TRUE)) %>%
            group_by(ID,site,date) %>%
              summarize(maxEARsum = sum(maxEAR)) %>%
            group_by(ID,site) %>%
              summarize(maxEARsumSite = max(maxEARsum))

**Comment by ldecicco-USGS** [comment]
Ha, I just editted it for you. Use triple back-ticks

**Comment by ldecicco-USGS** [comment]
OK, I thought we were getting rid of the sum, but that makes sense to me....let's see what happens....

**Comment by srcorsi-USGS** [comment]
We were getting rid of the summation of the same chemical per AOP in each sample, but still summing the max EAR per chemical per sample.

**Comment by ldecicco-USGS** [comment]
Hmm....this makes the heat map much more challenging to figure out the relevant endpoints

**Comment by srcorsi-USGS** [comment]
OK, here is what I now think the formula should be:
![image](https://user-images.githubusercontent.com/1444781/40205033-2f28e3d6-59f0-11e8-8374-f2208942cbb1.png)

maybe...

**Comment by srcorsi-USGS** [comment]
For the heatmap, here are my initial thoughts

1. For each endpoint, sum the EARs for each sample
2. Take the max EAR for each endpoint, AOP combo.

At one point, we talked about using a mean for the heatmap rather than a max. I remember it making sense then, but can't recall the reasoning for that now.

**Comment by ldecicco-USGS** [comment]
But only using the endpoints that fall out from the boxplots, right?

**Comment by ldecicco-USGS** [comment]
Which is the real kicker now that we're summing

**Comment by srcorsi-USGS** [comment]
yeah, still working on this. It gets a little perplexing.

**Comment by srcorsi-USGS** [comment]
OK, my thoughts now:
first get the EARs filtered down to the max per chem per site per AOP, retaining which endpoint the max comes from.

Then filter down to the endPoints that are still present.

Then take the max per endPoint:AOP combo.

Does that do it?

**Comment by srcorsi-USGS** [comment]
Well, this is the starting point to find max EAR by chem, but we loose endpoint when we do this.

```
heatInit  <- chemicalSummary %>%
    filter(EAR>0) %>%
    left_join(AOP, by="endPoint") %>%
    group_by(ID,site,date,chnm) %>%
    summarize(maxEAR = max(EAR, na.rm=TRUE))
```

How do we retain which endpoint the max came from?

**Comment by ldecicco-USGS** [comment]
Here's what I was starting:
```
boxData_max <- chemicalSummary %>%
  left_join(AOP, by="endPoint") %>%
  group_by(ID, chnm, site, date) %>%
  summarize(maxEAR = max(EAR, na.rm = TRUE),
            endPoint_used = endPoint[which.max(EAR)]) %>%
  ungroup()

boxData <- boxData_max %>%
  group_by(ID,site,date) %>%
  summarize(maxEARsum = sum(maxEAR)) %>%
  group_by(ID, site) %>%
  summarize(maxEAR = max(maxEARsum, na.rm = TRUE),
            date_picked = date[which.max(maxEARsum)]) %>%
  ungroup() %>%
  filter(!is.na(ID),
         maxEAR > ear_thresh) %>%
  mutate(ID = as.factor(ID))
```

**Comment by ldecicco-USGS** [comment]
Then, for the heat map:
```
chem_sum_AOP <- select(chemicalSummary, EAR, site, endPoint, chnm, date) %>%
  right_join(boxData, by=c("site","date"="date_picked")) %>%
  filter(endPoint %in% ep_priorities) %>%
  group_by(ID, endPoint) %>%
  summarize(maxEAR = max(EAR, na.rm = TRUE),
            meanEAR = mean(EAR, na.rm = TRUE),
            medianEAR = median(EAR, na.rm = TRUE)) %>%
  data.frame() %>%
  filter(!is.na(ID),
         medianEAR > 0) %>%
  mutate(ID = as.factor(ID),
         endPoint = as.factor(endPoint)) 
```

**Comment by ldecicco-USGS** [comment]
There's still too many endPoints for a pretty graph. I added in the `medianEAR > 0` filter...but that's kind of arbitrary

**Comment by ldecicco-USGS** [comment]
Sorry, I left out some code, here's the whole thing:
```
boxData_max <- chemicalSummary %>%
  left_join(AOP, by="endPoint") %>%
  group_by(ID, chnm, site, date) %>%
  summarize(maxEAR = max(EAR, na.rm = TRUE),
            endPoint_used = endPoint[which.max(EAR)]) %>%
  ungroup()

boxData <- boxData_max %>%
  group_by(ID,site,date) %>%
  summarize(maxEARsum = sum(maxEAR)) %>%
  group_by(ID, site) %>%
  summarize(maxEAR = max(maxEARsum, na.rm = TRUE),
            date_picked = date[which.max(maxEARsum)]) %>%
  ungroup() %>%
  filter(!is.na(ID),
         maxEAR > ear_thresh) %>%
  mutate(ID = as.factor(ID))

priority_AOPs <- boxData %>%
  group_by(ID) %>%
  summarise(siteDet = n_distinct(site)) %>%
  filter(siteDet >= siteThres)

boxData <- filter(boxData, ID %in% priority_AOPs$ID)

ep_priorities <- unique(boxData_max$endPoint_used)

chem_sum_AOP <- select(chemicalSummary, EAR, site, endPoint, chnm, date) %>%
  right_join(boxData, by=c("site","date"="date_picked")) %>%
  filter(endPoint %in% ep_priorities) %>%
  group_by(ID, endPoint) %>%
  summarize(maxEAR = max(EAR, na.rm = TRUE),
            meanEAR = mean(EAR, na.rm = TRUE),
            medianEAR = median(EAR, na.rm = TRUE)) %>%
  data.frame() %>%
  filter(!is.na(ID),
         medianEAR > 0) %>%
  mutate(ID = as.factor(ID),
         endPoint = as.factor(endPoint)) 
```

**Comment by srcorsi-USGS** [comment]
Shoot, I have been forgetting to filter by 10 or more sites with EAR > 0.001. That is what reduced the endpoints down.

**Comment by srcorsi-USGS** [comment]
OK, so your code here leaves us with 23 endpoints and 49 AOPs. Dan's file has 47 AOPs adn 22 unique endpoints. We are pretty close. Not sure what has changed. Either way, it is pretty managable.

**Comment by ldecicco-USGS** [comment]
It does...but like I said, filtering out the ` medianEAR > 0` is kind of :woman_shrugging: something I just threw in to make it look nicer

**Comment by srcorsi-USGS** [comment]
OK, I didn't catch that. So, what did we have previously that got us down to  47 AOPs and 22 unique endpoints? Did something change in the code? I guess it must have. My brain may comprehend this better in the morning.

**Comment by srcorsi-USGS** [comment]
The good news is that all of the AOPs that Dan just went through are all in the current dataframe chem_sum_AOP.

**Comment by ldecicco-USGS** [comment]
We were only looking at the max endpoint for each ID/site. So it was very straight-forward way to trim down endpoints.

Now we're taking the max endpoint at a sample per chemical...summing all the max endpoint/chemical per site, and taking the max of that. That introduces a lot more endpoints.

**Comment by srcorsi-USGS** [comment]
One thing that reduces slightly from the start is to include a filter of EAR > 0 in the first bit of code:

```
boxData_max <- chemicalSummary %>%
  filter(EAR > 0) %>%
  left_join(AOP, by="endPoint") %>%
  group_by(ID, chnm, site, date) %>%
  summarize(maxEAR = max(EAR, na.rm = TRUE),
            endPoint_used = endPoint[which.max(EAR)]) %>%
  ungroup()
```

That reduces from 123 to 94 endpoints. It is still too much, so let's try this:

1. For each AOP, determine the percent of influence from each endpoint by sample.
2. Remove endpoints that do not contribute at least X percent. In the initial analysis that I did when we had Dan develop AOP networks, I used X = 5% (but that was for chemical contributions rather than endpoints).

Let's see where that gets us with endpoint numbers. If it works out, we can move ahead and plan what SI info will be necessary to help support the final analysis.

**Comment by srcorsi-USGS** [comment]
Just checked whether EARendpoint >= X would help, and not really until you get to relatively high EAR levels. Checking on % now.

**Comment by ldecicco-USGS** [comment]
![image](https://user-images.githubusercontent.com/1105215/40257396-ad6658fa-5ab3-11e8-9342-784e889eba0d.png)

That's with using the endpoints that contribute at least 50% to the totals (I think...)

I still need to clean up the labels and color by relevance...but I'll push the code I used up. 

Now we have 3 ways to filter the data:
ear_thresh <- 0.001
siteThres <- 10
ep_percent_thres <- 0.5

**Comment by srcorsi-USGS** [comment]
Hmmm, 50% seems a bit high. What might be an answer here is to use something like this for initial prioritization in the manuscript, and then put a full blown fig into the SI that takes a whole page to display.

One question: the heat map looks to me to represent things unexpectedly. For instance, AOPs 35 and 38 have boxplot values between 10^-3 and 10^-2. AOPs 29 and 30 are more than an order of magnitude higher, but the heatmaps for those 4 all look basically the same. Am I missing something in this interpretation?

**Comment by ldecicco-USGS** [comment]
I haven't remotely tried to optimize the color scaling. While I'm doing that, we are plotting AOP ID 57 and 214 which Dan didn't summarize.

**Comment by ldecicco-USGS** [comment]
![image](https://user-images.githubusercontent.com/1105215/40258714-1686c05a-5ab8-11e8-9aac-05eecc982e17.png)

**Comment by srcorsi-USGS** [comment]
OK, maybe color optimization will sort it out.

Once we feel confident we have a final version, we can go back to Dan for revisions. For now, we should have enough info to get things in line.

There were 4 AOPs in Dan's relevance doc that indicated hepatic steatosis is not relevant to wildlife. AOP 57 is related to hepatic steatosis, so that one will be a no. Not sure about 214.

**Comment by srcorsi-USGS** [comment]
It's pretty clear from the colored boxplots which AOPs will be important in our data set. The boxplots really highlight it well.

**Comment by ldecicco-USGS** [comment]
We need to double-check what's happening (and what we want to happen) with the heat map. I think I re-jiggered it to be more consistent. I'm going to have to leave real soon. I just pushed a few more minor changes that make it so you are producing this graph:

![image](https://user-images.githubusercontent.com/1105215/40259121-6541922c-5aba-11e8-8002-b9f29c56f03b.png)

We'll get the site numbers and cleaner AOP id's back when the graph's ready, for now, let's keep the legends in there until we're happy with what's being plotted.

**Comment by srcorsi-USGS** [comment]
We could narrow down the endpoints in a way that is consistent with the rest of the manuscript by:

Use only the endpoints from Fig 3 (those endpoints with EAR > 10^-3 at 10 or more sites). I think we went away from this for fig 4 in favor of all endpoints that contribute to AOPs that have EAR > 10^-3 at 10 or more sites. That decision increased the number of endpoints in consideration. 

I do like using the percent contribution options, but it doesn't seem like there will be a reasonable way to reduce endpoints. Using just the fig 3 endpoints, filtering out the ones without AOPs, and then adding the full set of site by site tables that I suggested for the new SI table should cover all bases. We will still be highlighting the endpoints with highest priority. 

It might be time for another face to face talk about details to make sure we are not missing something with this concept.

**Comment by srcorsi-USGS** [comment]
Panel labels: I have written text in the manuscript using the top as panel "A" and the bottom as panel "B".

**Comment by ldecicco-USGS** [comment]
OK, using the endpoint filter from fig 3

Sent from 34000 ft in the air:
![aop_cow](https://user-images.githubusercontent.com/1105215/40442024-3e9268c8-5e88-11e8-8a8e-3c3e488682f8.png)

**Comment by srcorsi-USGS** [comment]
That's a pretty high-flying figure! It looks to me like a pretty manageable way to reduce endpoints displayed. The consistency with fig 3 will make it flow nicer through the manuscript. 

I do think we need to keep the full EARsum for each AOP in the boxplots. I don't think I explained that well originally. So:
1. Boxplots include all of the endpoints
2. Narrow down the endpoints displayed using fig 3 logic.

I will write the figure caption to reflect this.

**Comment by ldecicco-USGS** [comment]
![aop_cow](https://user-images.githubusercontent.com/1105215/40444295-97ee8f9a-5e8e-11e8-82a2-2c36a7007943.png)

**Comment by srcorsi-USGS** [comment]
I get two separate png files from this now. One with suffix "leg". Which to use?

**Comment by ldecicco-USGS** [comment]
plots/aop_cow.png

**Comment by srcorsi-USGS** [comment]
This looks good now. I can bring up the fig 4 script, run it, and it works out well. Oddly, when I "source" it from the create all figs script, it gives me a blank png file. For now, I have just run the script directly, and moved on.

**Comment by ldecicco-USGS** [comment]
Pushed up some updates. The resulting graph should look like:

![fig4_aop_cow](https://user-images.githubusercontent.com/1105215/40805467-f7b5c500-64e3-11e8-9a22-b65015de8192.png)

**Comment by srcorsi-USGS** [comment]
Observation: there are no points indicating outliers in the boxplots here. Is it that there really are no outliers, or were they suppressed somehow in the plot function?

**Comment by srcorsi-USGS** [comment]
@ldecicco-USGS : Double check on the outliers comment above.

**Comment by ldecicco-USGS** [comment]
No outliers
