### ISSUE TITLE
change SI table numbers due to insertion of new Table SI-7

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/toxManuscript#62]
Change name of table SI-7 to SI-8

Change name of table SI-8 to SI-9

These need to be changed in the code. This has been done in the text
@ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
1. I'm only aware of SI-7 (ie...not sure how to change 8->9)
2. Are we using "BPA_included" or the original? for the (new) SI8?
