### ISSUE TITLE
new benchmarks and import error

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/toxManuscript#8]
I have added rows to the benchmarks tab to fill in some pesticides. I changed only the benchmarks tab. Now running source("data_setup_wq_benchmarks.R") gives me an error "non-numeric argument to binary operator." I changed the CAS column to text and the Value column to numeric. Still the same error. Any ideas what that is? @ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
There were some "<" signs in the value columns fyi.
